jobs:
  include:
    - stage: test
      name: flask application tests
      language: python
      python: 3.6
      install: 
        - pip install -r requirements.txt
      script:
        - python test.py
    - stage: test
      name: JS app tests
      language: node_js
      node_js: 10.16.3
      install:
        - npm install --save-dev ava
        - npm install --save-dev browser-env
      script:
        - npm test
    - stage: deploy
      name: deploy to heroku
      script: skip
      deploy: &heroku
        provider: heroku
        api_key: $HEROKU_TOKEN
        app: lego-heroku-control
        on:
          repo: tommcn/lego-heroku-control
    - stage: deploy
      name: deploy to github pages
      script: skip
      before_deploy: cp -R static/ templates/
      deploy: &pages
        provider: pages
        skip_cleanup: true          
        github_token: $GITHUB_TOKEN
        local_dir: 
          - templates   
          - static