matrix:
  include:
    - stage: test
      language: python
      python: 
        - 3.6
      install: 
        - pip install -r requirements.txt
      script:
        - python test.py
    - stage: test
      language: node_js
      node_js:
        - 10.16.3
      install:
        - npm install --save-dev ava
        - npm install --save-dev browser-env
      script:
        - npm test
    - stage: deploy
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          secure: ${key}
        app: lego-heroku-control
        on:
          repo: tommcn/lego-heroku-control
              